# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 21:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('modelo', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2016), django.core.validators.MinValueValidator(1975)])),
                ('linea', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=50)),
                ('polarizado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('fechaOrigen', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='automovil',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automoviles.Marca'),
        ),
    ]
